### ISSUE TITLE
isTank

### ISSUE THREAD

**Issue by SpaceMonkeh** [Owyn/aaguide#2]
The RK9 guide you refer to uses an is tank function that changes the messages for the tanks so that they don't have to remember that it's opposite all the time. 

Is there any chance to implement that function here as well? (seeing how this dung requires even faster reflexes) It would be great for it to work perfectly on either tank or dps where the guide understand the role, and even a function to choose/change role on guide would be good for those warriors that tank.

Appreciate the work and gl!

**Comment by Owyn** [comment]
> The RK9 guide you refer to uses an is tank function that changes the messages for the tanks so that they don't have to remember that it's opposite all the time.

No it doesn't.

It has a check whenever user is a tank but it's used only to announce few front stuns on 1st and 2nd boss.

I'm following the design of rk9guide so no.

**Comment by Owyn** [comment]
Thought, you can just look at items spawned at safe side in new version.
