### ISSUE TITLE
items do not spawn at all

### ISSUE THREAD

**Issue by 542673** [Owyn/aaguide#6]
Safe zone signs just do not spawn

**Comment by Owyn** [comment]
works fine for me, was there 10 minutes ago

![tera_screenshot_20190203_021425_proc](https://user-images.githubusercontent.com/1309656/52170618-ad55c800-275e-11e9-94a8-96ee628d8fb5.jpg)

**Comment by Owyn** [comment]
should be fixed in latest update. (at least beam item should spawn)
